language: ruby
rvm:
  - 2.3.0
cache: bundler
env:
  - DB=postgresql
bundler_args: --without development
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rspec spec
before_install:
  - cp config/database.travis.yml config/database.yml
