default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: radar_development

test:
  <<: *default
  database: radar_test

production:
  <<: *default
  database: <%= ENV['RADAR_DATABASE_NAME'] %>
  username: <%= ENV['RADAR_DATABASE_USERNAME'] %>
  host: <%= ENV['RADAR_DATABASE_HOST'] %>
  password: <%= ENV['RADAR_DATABASE_PASSWORD'] %>
